<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'Parsedown' => array($vendorDir . '/erusev/parsedown'),
    'PEAR' => array($vendorDir . '/pear/pear_exception'),
    'Net' => array($vendorDir . '/pear/net_idna2'),
    'HTMLPurifier' => array($vendorDir . '/ezyang/htmlpurifier/library'),
);
