<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    'Pelago\\' => array($vendorDir . '/pelago/emogrifier/Classes'),
);
