<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = $vendorDir;

return array(
    'Parsedown' => array($vendorDir . '/erusev/parsedown'),
    'HTMLPurifier' => array($vendorDir . '/ezyang/htmlpurifier/library'),
);
