<?php

// include_paths.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = $vendorDir;

return array(
    $vendorDir . '/pear/net_idna2',
    $vendorDir . '/pear/pear_exception',
);
