<?php
use wcf\system\database\util\PreparedStatementConditionBuilder;
use wcf\system\language\LanguageFactory;
use wcf\system\WCF;

/**
 * @author	Alexander Ebert
 * @copyright	2001-2018 WoltLab GmbH
 * @license	GNU Lesser General Public License <http://opensource.org/licenses/lgpl-license.php>
 * @package	WoltLabSuite\Core
 */

// the content below is the effective result of `wcf\data\package\Package::writeConfigFile()`
// but the class is already in memory during the upgrade, causing the old version of this
// method to be used, which is not aware of `app.config.inc.php`

$content_de = <<<CONTENT_DE
<h2>1. Datenschutz auf einen Blick</h2>
<h3>Allgemeine Hinweise</h3> <p>Die folgenden Hinweise geben einen einfachen Überblick darüber, was mit Ihren personenbezogenen Daten passiert, wenn Sie unsere Website besuchen. Personenbezogene Daten sind alle Daten, mit denen Sie persönlich identifiziert werden können. Ausführliche Informationen zum Thema Datenschutz entnehmen Sie unserer unter diesem Text aufgeführten Datenschutzerklärung.</p>
<h3>Datenerfassung auf unserer Website</h3> <p><strong>Wer ist verantwortlich für die Datenerfassung auf dieser Website?</strong></p><p><br></p><p>Die Datenverarbeitung auf dieser Website erfolgt durch den Websitebetreiber. Dessen Kontaktdaten können Sie dem Impressum dieser Website entnehmen.</p><p><br></p><p><strong>Wie erfassen wir Ihre Daten?</strong></p><p><br></p><p>Ihre Daten werden zum einen dadurch erhoben, dass Sie uns diese mitteilen. Hierbei kann es sich z.B. um Daten handeln, die Sie in ein Kontaktformular eingeben.</p><p><br></p><p>Andere Daten werden automatisch beim Besuch der Website durch unsere IT-Systeme erfasst. Das sind vor allem technische Daten (z.B. Internetbrowser, Betriebssystem oder Uhrzeit des Seitenaufrufs). Die Erfassung dieser Daten erfolgt automatisch, sobald Sie unsere Website betreten.</p><p><br></p><p><strong>Wofür nutzen wir Ihre Daten?</strong></p><p><br></p><p>Ein Teil der Daten wird erhoben, um eine fehlerfreie Bereitstellung der Website zu gewährleisten. Andere Daten können zur Analyse Ihres Nutzerverhaltens verwendet werden.</p><p><br></p><p><strong>Welche Rechte haben Sie bezüglich Ihrer Daten?</strong></p><p><br></p><p>Sie haben jederzeit das Recht unentgeltlich Auskunft über Herkunft, Empfänger und Zweck Ihrer gespeicherten personenbezogenen Daten zu erhalten. Sie haben außerdem ein Recht, die Berichtigung, Sperrung oder Löschung dieser Daten zu verlangen. Hierzu sowie zu weiteren Fragen zum Thema Datenschutz können Sie sich jederzeit unter der im Impressum angegebenen Adresse an uns wenden. Des Weiteren steht Ihnen ein Beschwerderecht bei der zuständigen Aufsichtsbehörde zu.</p>

<h2>2. Allgemeine Hinweise und Pflichtinformationen</h2>
<h3>Datenschutz</h3> <p>Die Betreiber dieser Seiten nehmen den Schutz Ihrer persönlichen Daten sehr ernst. Wir behandeln Ihre personenbezogenen Daten vertraulich und entsprechend der gesetzlichen Datenschutzvorschriften sowie dieser Datenschutzerklärung.</p><p><br></p><p>Wenn Sie diese Website benutzen, werden verschiedene personenbezogene Daten erhoben. Personenbezogene Daten sind Daten, mit denen Sie persönlich identifiziert werden können. Die vorliegende Datenschutzerklärung erläutert, welche Daten wir erheben und wofür wir sie nutzen. Sie erläutert auch, wie und zu welchem Zweck das geschieht.</p><p><br></p><p>Wir weisen darauf hin, dass die Datenübertragung im Internet (z.B. bei der Kommunikation per E-Mail) Sicherheitslücken aufweisen kann. Ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht möglich.</p>
<h3>Hinweis zur verantwortlichen Stelle</h3> <p>Die verantwortliche Stelle für die Datenverarbeitung auf dieser Website ist:</p><p><br></p><p>[Name und Anschrift der verantwortlichen Stelle]</p>
<p>Telefon: [Telefonnummer der verantwortlichen Stelle]<br />
E-Mail: [E-Mail-Adresse der verantwortlichen Stelle]</p>
<p>Verantwortliche Stelle ist die natürliche oder juristische Person, die allein oder gemeinsam mit anderen über die Zwecke und Mittel der Verarbeitung von personenbezogenen Daten (z.B. Namen, E-Mail-Adressen o. Ä.) entscheidet.</p>
<h3>Widerruf Ihrer Einwilligung zur Datenverarbeitung</h3> <p>Viele Datenverarbeitungsvorgänge sind nur mit Ihrer ausdrücklichen Einwilligung möglich. Sie können eine bereits erteilte Einwilligung jederzeit widerrufen. Dazu reicht eine formlose Mitteilung per E-Mail an uns. Die Rechtmäßigkeit der bis zum Widerruf erfolgten Datenverarbeitung bleibt vom Widerruf unberührt.</p>
<h3>Beschwerderecht bei der zuständigen Aufsichtsbehörde</h3> <p>Im Falle datenschutzrechtlicher Verstöße steht dem Betroffenen ein Beschwerderecht bei der zuständigen Aufsichtsbehörde zu. Zuständige Aufsichtsbehörde in datenschutzrechtlichen Fragen ist der Landesdatenschutzbeauftragte des Bundeslandes, in dem unser Unternehmen seinen Sitz hat. Eine Liste der Datenschutzbeauftragten sowie deren Kontaktdaten können folgendem Link entnommen werden: <a href="https://www.bfdi.bund.de/DE/Infothek/Anschriften_Links/anschriften_links-node.html" target="_blank">https://www.bfdi.bund.de/DE/Infothek/Anschriften_Links/anschriften_links-node.html</a>.</p>
<h3>Recht auf Datenübertragbarkeit</h3> <p>Sie haben das Recht, Daten, die wir auf Grundlage Ihrer Einwilligung oder in Erfüllung eines Vertrags automatisiert verarbeiten, an sich oder an einen Dritten in einem gängigen, maschinenlesbaren Format aushändigen zu lassen. Sofern Sie die direkte Übertragung der Daten an einen anderen Verantwortlichen verlangen, erfolgt dies nur, soweit es technisch machbar ist.</p>
<h3>Auskunft, Sperrung, Löschung</h3> <p>Sie haben im Rahmen der geltenden gesetzlichen Bestimmungen jederzeit das Recht auf unentgeltliche Auskunft über Ihre gespeicherten personenbezogenen Daten, deren Herkunft und Empfänger und den Zweck der Datenverarbeitung und ggf. ein Recht auf Berichtigung, Sperrung oder Löschung dieser Daten. Hierzu sowie zu weiteren Fragen zum Thema personenbezogene Daten können Sie sich jederzeit unter der im Impressum angegebenen Adresse an uns wenden.</p>
<h3>Widerspruch gegen Werbe-Mails</h3> <p>Der Nutzung von im Rahmen der Impressumspflicht veröffentlichten Kontaktdaten zur Übersendung von nicht ausdrücklich angeforderter Werbung und Informationsmaterialien wird hiermit widersprochen. Die Betreiber der Seiten behalten sich ausdrücklich rechtliche Schritte im Falle der unverlangten Zusendung von Werbeinformationen, etwa durch Spam-E-Mails, vor.</p>

<h2>3. Datenerfassung auf unserer Website</h2>
<h3>Cookies</h3> <p>Die Internetseiten verwenden teilweise so genannte Cookies. Cookies richten auf Ihrem Rechner keinen Schaden an und enthalten keine Viren. Cookies dienen dazu, unser Angebot nutzerfreundlicher, effektiver und sicherer zu machen. Cookies sind kleine Textdateien, die auf Ihrem Rechner abgelegt werden und die Ihr Browser speichert.</p><p><br></p><p>Die meisten der von uns verwendeten Cookies sind so genannte “Session-Cookies”. Sie werden nach Ende Ihres Besuchs automatisch gelöscht. Andere Cookies bleiben auf Ihrem Endgerät gespeichert bis Sie diese löschen. Diese Cookies ermöglichen es uns, Ihren Browser beim nächsten Besuch wiederzuerkennen.</p><p><br></p><p>Sie können Ihren Browser so einstellen, dass Sie über das Setzen von Cookies informiert werden und Cookies nur im Einzelfall erlauben, die Annahme von Cookies für bestimmte Fälle oder generell ausschließen sowie das automatische Löschen der Cookies beim Schließen des Browser aktivieren. Bei der Deaktivierung von Cookies kann die Funktionalität dieser Website eingeschränkt sein.</p><p><br></p><p>Cookies, die zur Durchführung des elektronischen Kommunikationsvorgangs oder zur Bereitstellung bestimmter, von Ihnen erwünschter Funktionen (z.B. Warenkorbfunktion) erforderlich sind, werden auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO gespeichert. Der Websitebetreiber hat ein berechtigtes Interesse an der Speicherung von Cookies zur technisch fehlerfreien und optimierten Bereitstellung seiner Dienste. Soweit andere Cookies (z.B. Cookies zur Analyse Ihres Surfverhaltens) gespeichert werden, werden diese in dieser Datenschutzerklärung gesondert behandelt.</p>
<h3>Server-Log-Dateien</h3> <p>Der Provider der Seiten erhebt und speichert automatisch Informationen in so genannten Server-Log-Dateien, die Ihr Browser automatisch an uns übermittelt. Dies sind:</p> <ul> <li>Browsertyp und Browserversion</li> <li>verwendetes Betriebssystem</li> <li>Referrer URL</li> <li>Hostname des zugreifenden Rechners</li> <li>Uhrzeit der Serveranfrage</li> <li>IP-Adresse</li> </ul> <p>Eine Zusammenführung dieser Daten mit anderen Datenquellen wird nicht vorgenommen.</p><p><br></p><p>Grundlage für die Datenverarbeitung ist Art. 6 Abs. 1 lit. b DSGVO, der die Verarbeitung von Daten zur Erfüllung eines Vertrags oder vorvertraglicher Maßnahmen gestattet.</p>
<h3>Kontaktformular</h3> <p>Wenn Sie uns per Kontaktformular Anfragen zukommen lassen, werden Ihre Angaben aus dem Anfrageformular inklusive der von Ihnen dort angegebenen Kontaktdaten zwecks Bearbeitung der Anfrage und für den Fall von Anschlussfragen bei uns gespeichert. Diese Daten geben wir nicht ohne Ihre Einwilligung weiter.</p><p><br></p><p>Die Verarbeitung der in das Kontaktformular eingegebenen Daten erfolgt somit ausschließlich auf Grundlage Ihrer Einwilligung (Art. 6 Abs. 1 lit. a DSGVO). Sie können diese Einwilligung jederzeit widerrufen. Dazu reicht eine formlose Mitteilung per E-Mail an uns. Die Rechtmäßigkeit der bis zum Widerruf erfolgten Datenverarbeitungsvorgänge bleibt vom Widerruf unberührt.</p><p><br></p><p>Die von Ihnen im Kontaktformular eingegebenen Daten verbleiben bei uns, bis Sie uns zur Löschung auffordern, Ihre Einwilligung zur Speicherung widerrufen oder der Zweck für die Datenspeicherung entfällt (z.B. nach abgeschlossener Bearbeitung Ihrer Anfrage). Zwingende gesetzliche Bestimmungen – insbesondere Aufbewahrungsfristen – bleiben unberührt.</p>
<h3>Registrierung auf dieser Website</h3> <p>Sie können sich auf unserer Website registrieren, um zusätzliche Funktionen auf der Seite zu nutzen. Die dazu eingegebenen Daten verwenden wir nur zum Zwecke der Nutzung des jeweiligen Angebotes oder Dienstes, für den Sie sich registriert haben. Die bei der Registrierung abgefragten Pflichtangaben müssen vollständig angegeben werden. Anderenfalls werden wir die Registrierung ablehnen.</p><p><br></p><p>Für wichtige Änderungen etwa beim Angebotsumfang oder bei technisch notwendigen Änderungen nutzen wir die bei der Registrierung angegebene E-Mail-Adresse, um Sie auf diesem Wege zu informieren.</p><p><br></p><p>Die Verarbeitung der bei der Registrierung eingegebenen Daten erfolgt auf Grundlage Ihrer Einwilligung (Art. 6 Abs. 1 lit. a DSGVO). Sie können eine von Ihnen erteilte Einwilligung jederzeit widerrufen. Dazu reicht eine formlose Mitteilung per E-Mail an uns. Die Rechtmäßigkeit der bereits erfolgten Datenverarbeitung bleibt vom Widerruf unberührt.</p><p><br></p><p>Die bei der Registrierung erfassten Daten werden von uns gespeichert, solange Sie auf unserer Website registriert sind und werden anschließend gelöscht. Gesetzliche Aufbewahrungsfristen bleiben unberührt.</p>
<h3>Registrierung mit Facebook Connect</h3> <p>Statt einer direkten Registrierung auf unserer Website können Sie sich mit Facebook Connect registrieren. Anbieter dieses Dienstes ist die Facebook Ireland Limited, 4 Grand Canal Square, Dublin 2, Irland.</p><p><br></p><p>Wenn Sie sich für die Registrierung mit Facebook Connect entscheiden, werden Sie automatisch auf die Plattform von Facebook weitergeleitet. Dort können Sie sich mit Ihren Nutzungsdaten anmelden. Dadurch wird Ihr Facebook-Profil mit unserer Website bzw. unseren Diensten verknüpft. Durch diese Verknüpfung erhalten wir Zugriff auf Ihre bei Facebook hinterlegten Daten. Dies sind vor allem:</p> <ul> <li>Facebook-Name</li> <li>Facebook-Profilbild</li> <li>bei Facebook hinterlegte E-Mail-Adresse</li> <li>Facebook-ID</li> <li>Geburtstag</li> <li>Geschlecht</li> <li>Land</li> </ul> <p>Diese Daten werden zur Einrichtung, Bereitstellung und Personalisierung Ihres Accounts genutzt.</p><p><br></p><p>Weitere Informationen finden Sie in den Facebook-Nutzungsbedingungen und den Facebook-Datenschutzbestimmungen. Diese finden Sie unter: <a href="https://de-de.facebook.com/about/privacy/" target="_blank">https://de-de.facebook.com/about/privacy/</a> und <a href="https://www.facebook.com/legal/terms/" target="_blank">https://www.facebook.com/legal/terms/</a>.</p>
<h3>Registrierung mit Google+</h3> <p>Statt einer direkten Registrierung auf unserer Website können Sie sich mit Google+ registrieren. Anbieter dieses Dienstes ist die Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA.</p><p><br></p><p>Wenn Sie sich für die Registrierung mit Google+ entscheiden, werden Sie automatisch auf die Plattform von Google+ weitergeleitet. Dort können Sie sich mit Ihren Nutzungsdaten anmelden. Dadurch wird Ihr Google+-Profil mit unserer Website bzw. unseren Diensten verknüpft. Durch diese Verknüpfung erhalten wir Zugriff auf Ihre bei Google+ hinterlegten Daten. Dies sind vor allem:</p> <ul> <li>Google+-Name</li> <li>Google+-Profilbild</li> <li>bei Google+ hinterlegte E-Mail-Adresse</li> <li>Google+-ID</li>  <li>Geburtstag</li> <li>Geschlecht</li> <li>Land</li> </ul> <p>Diese Daten werden zur Einrichtung, Bereitstellung und Personalisierung Ihres Accounts genutzt.</p><p><br></p><p>Weitere Informationen finden Sie in den Google-Nutzungsbedingungen, Google+-Nutzungsbedingungen und den Google-Datenschutzbestimmungen. Diese finden Sie unter: <a href="https://policies.google.com/terms?hl=de" target="_blank">https://policies.google.com/terms?hl=de</a>, <a href="https://www.google.com/intl/de/+/policy/pagesterms.html" target="_blank">https://www.google.com/intl/de/+/policy/pagesterms.html</a> und <a href="https://policies.google.com/privacy?hl=de" target="_blank">https://policies.google.com/privacy?hl=de</a>.</p>
<h3>Registrierung mit Twitter</h3> <p>Statt einer direkten Registrierung auf unserer Website können Sie sich mit Twitter registrieren. Anbieter dieses Dienstes ist die Twitter Inc., 1355 Market Street, Suite 900, San Francisco, CA 94103, USA.</p><p><br></p><p>Wenn Sie sich für die Registrierung mit Twitter entscheiden, werden Sie automatisch auf die Plattform von Twitter weitergeleitet. Dort können Sie sich mit Ihren Nutzungsdaten anmelden. Dadurch wird Ihr Twitter-Profil mit unserer Website bzw. unseren Diensten verknüpft. Durch diese Verknüpfung erhalten wir Zugriff auf Ihre bei Twitter hinterlegten Daten. Dies sind vor allem:</p> <ul> <li>Twitter-Name</li> <li>Twitter-Profilbild</li> <li>bei Twitter hinterlegte E-Mail-Adresse</li> <li>Twitter-ID</li>  <li>Geburtstag</li> <li>Geschlecht</li> <li>Land</li> </ul> <p>Diese Daten werden zur Einrichtung, Bereitstellung und Personalisierung Ihres Accounts genutzt.</p><p><br></p><p>Weitere Informationen finden Sie in den Twitter-Nutzungsbedingungen und den Twitter-Datenschutzbestimmungen. Diese finden Sie unter: <a href="https://twitter.com/de/tos" target="_blank">https://twitter.com/de/tos</a> und <a href="https://twitter.com/de/privacy" target="_blank">https://twitter.com/de/privacy</a>.</p>
<h3>Registrierung mit GitHub</h3> <p>Statt einer direkten Registrierung auf unserer Website können Sie sich mit GitHub registrieren. Anbieter dieses Dienstes ist die GitHub, Inc, 88 Colin P Kelly Jr St, San Francisco, CA 94107, USA.</p><p><br></p><p>Wenn Sie sich für die Registrierung mit GitHub entscheiden, werden Sie automatisch auf die Plattform von GitHub weitergeleitet. Dort können Sie sich mit Ihren Nutzungsdaten anmelden. Dadurch wird Ihr GitHub-Profil mit unserer Website bzw. unseren Diensten verknüpft. Durch diese Verknüpfung erhalten wir Zugriff auf Ihre bei GitHub hinterlegten Daten. Dies sind vor allem:</p> <ul> <li>GitHub-Name</li> <li>GitHub-Profilbild</li> <li>bei GitHub hinterlegte E-Mail-Adresse</li> <li>GitHub-ID</li>  <li>Geburtstag</li> <li>Geschlecht</li> <li>Land</li> </ul> <p>Diese Daten werden zur Einrichtung, Bereitstellung und Personalisierung Ihres Accounts genutzt.</p><p><br></p><p>Weitere Informationen finden Sie in den GitHub-Nutzungsbedingungen und den GitHub-Datenschutzbestimmungen. Diese finden Sie unter: <a href="https://help.github.com/articles/github-terms-of-service/" target="_blank">https://help.github.com/articles/github-terms-of-service/</a> und <a href="https://help.github.com/articles/github-privacy-statement/" target="_blank">https://help.github.com/articles/github-privacy-statement/</a>.</p>
<h3>Verarbeiten von Daten (Kunden- und Vertragsdaten)</h3> <p>Wir erheben, verarbeiten und nutzen personenbezogene Daten nur, soweit sie für die Begründung, inhaltliche Ausgestaltung oder Änderung des Rechtsverhältnisses erforderlich sind (Bestandsdaten). Dies erfolgt auf Grundlage von Art. 6 Abs. 1 lit. b DSGVO, der die Verarbeitung von Daten zur Erfüllung eines Vertrags oder vorvertraglicher Maßnahmen gestattet. Personenbezogene Daten über die Inanspruchnahme unserer Internetseiten (Nutzungsdaten) erheben, verarbeiten und nutzen wir nur, soweit dies erforderlich ist, um dem Nutzer die Inanspruchnahme des Dienstes zu ermöglichen oder abzurechnen.</p><p><br></p><p>Die erhobenen Kundendaten werden nach Abschluss des Auftrags oder Beendigung der Geschäftsbeziehung gelöscht. Gesetzliche Aufbewahrungsfristen bleiben unberührt.</p>
<h3>Datenübermittlung bei Vertragsschluss für Dienstleistungen und digitale Inhalte</h3> <p>Wir übermitteln personenbezogene Daten an Dritte nur dann, wenn dies im Rahmen der Vertragsabwicklung notwendig ist, etwa an das mit der Zahlungsabwicklung beauftragte Kreditinstitut.</p><p><br></p><p>Eine weitergehende Übermittlung der Daten erfolgt nicht bzw. nur dann, wenn Sie der Übermittlung ausdrücklich zugestimmt haben. Eine Weitergabe Ihrer Daten an Dritte ohne ausdrückliche Einwilligung, etwa zu Zwecken der Werbung, erfolgt nicht.</p><p><br></p><p>Grundlage für die Datenverarbeitung ist Art. 6 Abs. 1 lit. b DSGVO, der die Verarbeitung von Daten zur Erfüllung eines Vertrags oder vorvertraglicher Maßnahmen gestattet.</p>

<h2>4. Analyse Tools und Werbung</h2>
<h3>Google reCAPTCHA</h3> <p>Wir nutzen “Google reCAPTCHA” (im Folgenden “reCAPTCHA”) auf unseren Websites. Anbieter ist die Google Inc., 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA (“Google”).</p><p><br></p><p>Mit reCAPTCHA soll überprüft werden, ob die Dateneingabe auf unseren Websites (z.B. in einem Kontaktformular) durch einen Menschen oder durch ein automatisiertes Programm erfolgt. Hierzu analysiert reCAPTCHA das Verhalten des Websitebesuchers anhand verschiedener Merkmale. Diese Analyse beginnt automatisch, sobald der Websitebesucher die Website betritt. Zur Analyse wertet reCAPTCHA verschiedene Informationen aus (z.B. IP-Adresse, Verweildauer des Websitebesuchers auf der Website oder vom Nutzer getätigte Mausbewegungen). Die bei der Analyse erfassten Daten werden an Google weitergeleitet.</p><p><br></p><p>Die reCAPTCHA-Analysen laufen vollständig im Hintergrund. Websitebesucher werden nicht darauf hingewiesen, dass eine Analyse stattfindet.</p><p><br></p><p>Die Datenverarbeitung erfolgt auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO. Der Websitebetreiber hat ein berechtigtes Interesse daran, seine Webangebote vor missbräuchlicher automatisierter Ausspähung und vor SPAM zu schützen.</p><p><br></p><p>Weitere Informationen zu Google reCAPTCHA sowie die Datenschutzerklärung von Google entnehmen Sie folgenden Links: <a href="https://www.google.com/intl/de/policies/privacy/" target="_blank">https://www.google.com/intl/de/policies/privacy/</a> und <a href="https://www.google.com/recaptcha/intro/android.html" target="_blank">https://www.google.com/recaptcha/intro/android.html</a>.</p>

<h2>5. Newsletter</h2>
<h3>Newsletterdaten</h3> <p>Wenn Sie den auf der Website angebotenen Newsletter beziehen möchten, benötigen wir von Ihnen eine E-Mail-Adresse sowie Informationen, welche uns die Überprüfung gestatten, dass Sie der Inhaber der angegebenen E-Mail-Adresse sind und mit dem Empfang des Newsletters einverstanden sind. Weitere Daten werden nicht bzw. nur auf freiwilliger Basis erhoben. Diese Daten verwenden wir ausschließlich für den Versand der angeforderten Informationen und geben diese nicht an Dritte weiter.</p><p><br></p><p>Die Verarbeitung der in das Newsletteranmeldeformular eingegebenen Daten erfolgt ausschließlich auf Grundlage Ihrer Einwilligung (Art. 6 Abs. 1 lit. a DSGVO). Die erteilte Einwilligung zur Speicherung der Daten, der E-Mail-Adresse sowie deren Nutzung zum Versand des Newsletters können Sie jederzeit widerrufen, etwa über den "Austragen"-Link im Newsletter. Die Rechtmäßigkeit der bereits erfolgten Datenverarbeitungsvorgänge bleibt vom Widerruf unberührt.</p><p><br></p><p>Die von Ihnen zum Zwecke des Newsletter-Bezugs bei uns hinterlegten Daten werden von uns bis zu Ihrer Austragung aus dem Newsletter gespeichert und nach der Abbestellung des Newsletters gelöscht. Daten, die zu anderen Zwecken bei uns gespeichert wurden (z.B. E-Mail-Adressen für den Mitgliederbereich) bleiben hiervon unberührt.</p>

<h2>6. Plugins und Tools</h2>
<h3>YouTube</h3> <p>Unsere Website nutzt Plugins der von Google betriebenen Seite YouTube. Betreiber der Seiten ist die YouTube, LLC, 901 Cherry Ave., San Bruno, CA 94066, USA.</p><p><br></p><p>Wenn Sie eine unserer mit einem YouTube-Plugin ausgestatteten Seiten besuchen, wird eine Verbindung zu den Servern von YouTube hergestellt. Dabei wird dem YouTube-Server mitgeteilt, welche unserer Seiten Sie besucht haben.</p><p><br></p><p>Wenn Sie in Ihrem YouTube-Account eingeloggt sind, ermöglichen Sie YouTube, Ihr Surfverhalten direkt Ihrem persönlichen Profil zuzuordnen. Dies können Sie verhindern, indem Sie sich aus Ihrem YouTube-Account ausloggen.</p><p><br></p><p>Die Nutzung von YouTube erfolgt im Interesse einer ansprechenden Darstellung unserer Online-Angebote. Dies stellt ein berechtigtes Interesse im Sinne von Art. 6 Abs. 1 lit. f DSGVO dar.</p><p><br></p><p>Weitere Informationen zum Umgang mit Nutzerdaten finden Sie in der Datenschutzerklärung von YouTube unter: <a href="https://www.google.de/intl/de/policies/privacy" target="_blank">https://www.google.de/intl/de/policies/privacy</a>.</p>
<h3>Google Web Fonts</h3> <p>Diese Seite nutzt zur einheitlichen Darstellung von Schriftarten so genannte Web Fonts, die von Google bereitgestellt werden. Beim Aufruf einer Seite lädt Ihr Browser die benötigten Web Fonts in ihren Browsercache, um Texte und Schriftarten korrekt anzuzeigen.</p><p><br></p><p>Zu diesem Zweck muss der von Ihnen verwendete Browser Verbindung zu den Servern von Google aufnehmen. Hierdurch erlangt Google Kenntnis darüber, dass über Ihre IP-Adresse unsere Website aufgerufen wurde. Die Nutzung von Google Web Fonts erfolgt im Interesse einer einheitlichen und ansprechenden Darstellung unserer Online-Angebote. Dies stellt ein berechtigtes Interesse im Sinne von Art. 6 Abs. 1 lit. f DSGVO dar.</p><p><br></p><p>Wenn Ihr Browser Web Fonts nicht unterstützt, wird eine Standardschrift von Ihrem Computer genutzt.</p><p><br></p><p>Weitere Informationen zu Google Web Fonts finden Sie unter <a href="https://developers.google.com/fonts/faq" target="_blank">https://developers.google.com/fonts/faq</a> und in der Datenschutzerklärung von Google: <a href="https://www.google.com/policies/privacy/" target="_blank">https://www.google.com/policies/privacy/</a>.</p>
<h3>Vimeo</h3> <p>Unsere Website nutzt Plugins des Videoportals Vimeo. Anbieter ist die Vimeo Inc., 555 West 18th Street, New York, New York 10011, USA.</p><p><br></p><p>Wenn Sie eine unserer mit einem Vimeo-Plugin ausgestatteten Seiten besuchen, wird eine Verbindung zu den Servern von Vimeo hergestellt. Dabei wird dem Vimeo-Server mitgeteilt, welche unserer Seiten Sie besucht haben. Zudem erlangt Vimeo Ihre IP-Adresse. Dies gilt auch dann, wenn Sie nicht bei Vimeo eingeloggt sind oder keinen Account bei Vimeo besitzen. Die von Vimeo erfassten Informationen werden an den Vimeo-Server in den USA übermittelt.</p><p><br></p><p>Wenn Sie in Ihrem Vimeo-Account eingeloggt sind, ermöglichen Sie Vimeo, Ihr Surfverhalten direkt Ihrem persönlichen Profil zuzuordnen. Dies können Sie verhindern, indem Sie sich aus Ihrem Vimeo-Account ausloggen.</p><p><br></p><p>Weitere Informationen zum Umgang mit Nutzerdaten finden Sie in der Datenschutzerklärung von Vimeo unter: <a href="https://vimeo.com/privacy" target="_blank">https://vimeo.com/privacy</a>.</p>
<h3>Google Maps</h3> <p>Diese Seite nutzt über eine API den Kartendienst Google Maps. Anbieter ist die Google Inc., 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA.</p><p><br></p><p>Zur Nutzung der Funktionen von Google Maps ist es notwendig, Ihre IP Adresse zu speichern. Diese Informationen werden in der Regel an einen Server von Google in den USA übertragen und dort gespeichert. Der Anbieter dieser Seite hat keinen Einfluss auf diese Datenübertragung.</p><p><br></p><p>Die Nutzung von Google Maps erfolgt im Interesse einer ansprechenden Darstellung unserer Online-Angebote und an einer leichten Auffindbarkeit der von uns auf der Website angegebenen Orte. Dies stellt ein berechtigtes Interesse im Sinne von Art. 6 Abs. 1 lit. f DSGVO dar.</p><p><br></p><p>Mehr Informationen zum Umgang mit Nutzerdaten finden Sie in der Datenschutzerklärung von Google: <a href="https://www.google.de/intl/de/policies/privacy/" target="_blank">https://www.google.de/intl/de/policies/privacy/</a>.</p>
<h3>SoundCloud</h3> <p>Auf unseren Seiten können Plugins des sozialen Netzwerks SoundCloud (SoundCloud Limited, Berners House, 47-48 Berners Street, London W1T 3NF, Großbritannien.) integriert sein. Die SoundCloud-Plugins erkennen Sie an dem SoundCloud-Logo auf den betroffenen Seiten.</p><p><br></p><p>Wenn Sie unsere Seiten besuchen, wird nach Aktivierung des Plugin eine direkte Verbindung zwischen Ihrem Browser und dem SoundCloud-Server hergestellt. SoundCloud erhält dadurch die Information, dass Sie mit Ihrer IP-Adresse unsere Seite besucht haben. Wenn Sie den “Like-Button” oder “Share-Button” anklicken während Sie in Ihrem SoundCloud- Benutzerkonto eingeloggt sind, können Sie die Inhalte unserer Seiten mit Ihrem SoundCloud-Profil verlinken und/oder teilen. Dadurch kann SoundCloud Ihrem Benutzerkonto den Besuch unserer Seiten zuordnen. Wir weisen darauf hin, dass wir als Anbieter der Seiten keine Kenntnis vom Inhalt der übermittelten Daten sowie deren Nutzung durch SoundCloud erhalten. Weitere Informationen hierzu finden Sie in der Datenschutzerklärung von SoundCloud unter: <a href="https://soundcloud.com/pages/privacy" target="_blank">https://soundcloud.com/pages/privacy</a>.</p><p><br></p><p>Wenn Sie nicht wünschen, dass SoundCloud den Besuch unserer Seiten Ihrem SoundCloud- Benutzerkonto zuordnet, loggen Sie sich bitte aus Ihrem SoundCloud-Benutzerkonto aus bevor Sie Inhalte des SoundCloud-Plugins aktivieren.</p>
<h3>Veoh</h3> <p>Unsere Website nutzt Plugins des Videoportals Veoh. Anbieter ist die FC2, 4730 South Fort Apache Road, Suite 300, Las Vegas, NV 89147, USA.</p><p><br></p><p>Wenn Sie eine unserer mit einem Veoh-Plugin ausgestatteten Seiten besuchen, wird eine Verbindung zu den Servern von Veoh hergestellt. Dabei wird dem Veoh-Server mitgeteilt, welche unserer Seiten Sie besucht haben. Zudem erlangt Veoh Ihre IP-Adresse. Dies gilt auch dann, wenn Sie nicht bei Veoh eingeloggt sind oder keinen Account bei Veoh besitzen. Die von Veoh erfassten Informationen werden an den Veoh-Server in den USA übermittelt.</p><p><br></p><p>Wenn Sie in Ihrem Veoh-Account eingeloggt sind, ermöglichen Sie Veoh, Ihr Surfverhalten direkt Ihrem persönlichen Profil zuzuordnen. Dies können Sie verhindern, indem Sie sich aus Ihrem Veoh-Account ausloggen.</p><p><br></p><p>Weitere Informationen zum Umgang mit Nutzerdaten finden Sie in der Datenschutzerklärung von Veoh unter: <a href="http://www.veoh.com/corporate/privacypolicy" target="_blank">http://www.veoh.com/corporate/privacypolicy</a>.</p>
<h3>Dailymotion</h3> <p>Unsere Website nutzt Plugins des Videoportals Dailymotion. Anbieter ist Dailymotion, 140 boulevard Malesherbes, 75017 Paris, Frankreich.</p><p><br></p><p>Wenn Sie eine unserer mit einem Dailymotion-Plugin ausgestatteten Seiten besuchen, wird eine Verbindung zu den Servern von Dailymotion hergestellt. Dabei wird dem Dailymotion-Server mitgeteilt, welche unserer Seiten Sie besucht haben. Zudem erlangt Dailymotion Ihre IP-Adresse. Dies gilt auch dann, wenn Sie nicht bei Dailymotion eingeloggt sind oder keinen Account bei Dailymotion besitzen.</p><p><br></p><p>Wenn Sie in Ihrem Dailymotion-Account eingeloggt sind, ermöglichen Sie Dailymotion, Ihr Surfverhalten direkt Ihrem persönlichen Profil zuzuordnen. Dies können Sie verhindern, indem Sie sich aus Ihrem Dailymotion-Account ausloggen.</p><p><br></p><p>Weitere Informationen zum Umgang mit Nutzerdaten finden Sie in der Datenschutzerklärung von Dailymotion unter: <a href="https://www.dailymotion.com/legal/privacy" target="_blank">https://www.dailymotion.com/legal/privacy</a>.</p>
<h3>GitHub</h3> <p>Unsere Website nutzt Plugins des Online-Dienstes GitHub. Anbieter ist GitHub, Inc, 88 Colin P Kelly Jr St, San Francisco, CA 94107, USA.</p><p><br></p><p>Wenn Sie eine unserer mit einem GitHub-Plugin ausgestatteten Seiten besuchen, wird eine Verbindung zu den Servern von GitHub hergestellt. Dabei wird dem GitHub-Server mitgeteilt, welche unserer Seiten Sie besucht haben. Zudem erlangt GitHub Ihre IP-Adresse. Dies gilt auch dann, wenn Sie nicht bei GitHub eingeloggt sind oder keinen Account bei GitHub besitzen. Die von GitHub erfassten Informationen werden an den GitHub-Server in den USA übermittelt.</p><p><br></p><p>Wenn Sie in Ihrem GitHub-Account eingeloggt sind, ermöglichen Sie GitHub, Ihr Surfverhalten direkt Ihrem persönlichen Profil zuzuordnen. Dies können Sie verhindern, indem Sie sich aus Ihrem GitHub-Account ausloggen.</p><p><br></p><p>Weitere Informationen zum Umgang mit Nutzerdaten finden Sie in der Datenschutzerklärung von GitHub unter: <a href="https://help.github.com/articles/github-privacy-statement/" target="_blank">https://help.github.com/articles/github-privacy-statement/</a>.</p>
<h3>Spotify</h3> <p>Unsere Website nutzt Plugins des Online-Dienstes Spotify. Anbieter ist die Spotify AB, Birger Jarlsgatan 61, 113 56 Stockholm, Schweden.</p><p><br></p><p>Wenn Sie eine unserer mit einem Spotify-Plugin ausgestatteten Seiten besuchen, wird eine Verbindung zu den Servern von Spotify hergestellt. Dabei wird dem Spotify-Server mitgeteilt, welche unserer Seiten Sie besucht haben. Zudem erlangt Spotify Ihre IP-Adresse. Dies gilt auch dann, wenn Sie nicht bei Spotify eingeloggt sind oder keinen Account bei Spotify besitzen.</p><p><br></p><p>Wenn Sie in Ihrem Spotify-Account eingeloggt sind, ermöglichen Sie Spotify, Ihr Surfverhalten direkt Ihrem persönlichen Profil zuzuordnen. Dies können Sie verhindern, indem Sie sich aus Ihrem Spotify-Account ausloggen.</p><p><br></p><p>Weitere Informationen zum Umgang mit Nutzerdaten finden Sie in der Datenschutzerklärung von Spotify unter: <a href="https://www.spotify.com/de/legal/privacy-policy/" target="_blank">https://www.spotify.com/de/legal/privacy-policy/</a>.</p>
<h3>Instagram</h3> <p>Unsere Website nutzt Plugins des Online-Dienstes Instagram. Anbieter ist Instagram Inc., 1601 Willow Road, Menlo Park, CA 94025, USA.</p><p><br></p><p>Wenn Sie eine unserer mit einem Instagram-Plugin ausgestatteten Seiten besuchen, wird eine Verbindung zu den Servern von Instagram hergestellt. Dabei wird dem Instagram-Server mitgeteilt, welche unserer Seiten Sie besucht haben. Zudem erlangt Instagram Ihre IP-Adresse. Dies gilt auch dann, wenn Sie nicht bei Instagram eingeloggt sind oder keinen Account bei Instagram besitzen. Die von Instagram erfassten Informationen werden an den Instagram-Server in den USA übermittelt.</p><p><br></p><p>Wenn Sie in Ihrem Instagram-Account eingeloggt sind, ermöglichen Sie Instagram, Ihr Surfverhalten direkt Ihrem persönlichen Profil zuzuordnen. Dies können Sie verhindern, indem Sie sich aus Ihrem Instagram-Account ausloggen.</p><p><br></p><p>Weitere Informationen zum Umgang mit Nutzerdaten finden Sie in der Datenschutzerklärung von Instagram unter: <a href="https://instagram.com/about/legal/privacy/" target="_blank">https://instagram.com/about/legal/privacy/</a>.</p>
<h3>Imgur</h3> <p>Unsere Website nutzt Plugins des Online-Dienstes Imgur. Anbieter ist Imgur, Inc., 415 Jackson Street, 2nd Floor, Suite 200, San Francisco, CA 94111, USA.</p><p><br></p><p>Wenn Sie eine unserer mit einem Imgur-Plugin ausgestatteten Seiten besuchen, wird eine Verbindung zu den Servern von Imgur hergestellt. Dabei wird dem Imgur-Server mitgeteilt, welche unserer Seiten Sie besucht haben. Zudem erlangt Imgur Ihre IP-Adresse. Dies gilt auch dann, wenn Sie nicht bei Imgur eingeloggt sind oder keinen Account bei Imgur besitzen. Die von Imgur erfassten Informationen werden an den Imgur-Server in den USA übermittelt.</p><p><br></p><p>Wenn Sie in Ihrem Imgur-Account eingeloggt sind, ermöglichen Sie Imgur, Ihr Surfverhalten direkt Ihrem persönlichen Profil zuzuordnen. Dies können Sie verhindern, indem Sie sich aus Ihrem Imgur-Account ausloggen.</p><p><br></p><p>Weitere Informationen zum Umgang mit Nutzerdaten finden Sie in der Datenschutzerklärung von Imgur unter: <a href="https://imgur.com/privacy" target="_blank">https://imgur.com/privacy</a>.</p>
<h3>Twitch</h3> <p>Unsere Website nutzt Plugins des Online-Dienstes Twitch. Anbieter ist Twitch Interactive, Inc., 225 Bush Street, 6th Floor, San Francisco, CA 94104, USA.</p><p><br></p><p>Wenn Sie eine unserer mit einem Twitch-Plugin ausgestatteten Seiten besuchen, wird eine Verbindung zu den Servern von Twitch hergestellt. Dabei wird dem Twitch-Server mitgeteilt, welche unserer Seiten Sie besucht haben. Zudem erlangt Twitch Ihre IP-Adresse. Dies gilt auch dann, wenn Sie nicht bei Twitch eingeloggt sind oder keinen Account bei Twitch besitzen. Die von Twitch erfassten Informationen werden an den Twitch-Server in den USA übermittelt.</p><p><br></p><p>Wenn Sie in Ihrem Twitch-Account eingeloggt sind, ermöglichen Sie Twitch, Ihr Surfverhalten direkt Ihrem persönlichen Profil zuzuordnen. Dies können Sie verhindern, indem Sie sich aus Ihrem Twitch-Account ausloggen.</p><p><br></p><p>Weitere Informationen zum Umgang mit Nutzerdaten finden Sie in der Datenschutzerklärung von Twitch unter: <a href="https://www.twitch.tv/p/legal/privacy-policy/" target="_blank">https://www.twitch.tv/p/legal/privacy-policy/</a>.</p>

<h2>7. Zahlungsanbieter</h2>
<h3>PayPal</h3> <p>Auf unserer Website bieten wir u.a. die Bezahlung via PayPal an. Anbieter dieses Zahlungsdienstes ist die PayPal (Europe) S.à.r.l. et Cie, S.C.A., 22-24 Boulevard Royal, L-2449 Luxembourg (im Folgenden “PayPal”).</p><p><br></p><p>Wenn Sie die Bezahlung via PayPal auswählen, werden die von Ihnen eingegebenen Zahlungsdaten an PayPal übermittelt.</p><p><br></p><p>Die Übermittlung Ihrer Daten an PayPal erfolgt auf Grundlage von Art. 6 Abs. 1 lit. a DSGVO (Einwilligung) und Art. 6 Abs. 1 lit. b DSGVO (Verarbeitung zur Erfüllung eines Vertrags). Sie haben die Möglichkeit, Ihre Einwilligung zur Datenverarbeitung jederzeit zu widerrufen. Ein Widerruf wirkt sich auf die Wirksamkeit von in der Vergangenheit liegenden Datenverarbeitungsvorgängen nicht aus.</p>
CONTENT_DE;

$content_en = <<<CONTENT_EN
<h2>1. An overview of data protection</h2>
<h3>General</h3> <p>The following gives a simple overview of what happens to your personal information when you visit our website. Personal information is any data with which you could be personally identified. Detailed information on the subject of data protection can be found in our privacy policy found below.</p>
<h3>Data collection on our website</h3> <p><strong>Who is responsible for the data collection on this website?</strong></p><p><br></p><p>The data collected on this website are processed by the website operator. The operator's contact details can be found in the website's required legal notice.</p><p><br></p><p><strong>How do we collect your data?</strong></p><p><br></p><p>Some data are collected when you provide it to us. This could, for example, be data you enter on a contact form.</p><p><br></p><p>Other data are collected automatically by our IT systems when you visit the website. These data are primarily technical data such as the browser and operating system you are using or when you accessed the page. These data are collected automatically as soon as you enter our website.</p><p><br></p><p><strong>What do we use your data for?</strong></p><p><br></p><p>Part of the data is collected to ensure the proper functioning of the website. Other data can be used to analyze how visitors use the site.</p><p><br></p><p><strong>What rights do you have regarding your data?</strong></p><p><br></p><p>You always have the right to request information about your stored data, its origin, its recipients, and the purpose of its collection at no charge. You also have the right to request that it be corrected, blocked, or deleted. You can contact us at any time using the address given in the legal notice if you have further questions about the issue of privacy and data protection. You may also, of course, file a complaint with the competent regulatory authorities.</p>

<h2>2. General information and mandatory information</h2>
<h3>Data protection</h3> <p>The operators of this website take the protection of your personal data very seriously. We treat your personal data as confidential and in accordance with the statutory data protection regulations and this privacy policy.</p><p><br></p><p>If you use this website, various pieces of personal data will be collected. Personal information is any data with which you could be personally identified. This privacy policy explains what information we collect and what we use it for. It also explains how and for what purpose this happens.</p><p><br></p><p>Please note that data transmitted via the internet (e.g. via email communication) may be subject to security breaches. Complete protection of your data from third-party access is not possible.</p>
<h3>Notice concerning the party responsible for this website</h3> <p>The party responsible for processing data on this website is:</p><p><br></p><p>[name and address of the responsible party]</p>
<p>Telephone: [telephone number of the responsible party]<br />
Email: [email address of the responsible party]</p>
<p>The responsible party is the natural or legal person who alone or jointly with others decides on the purposes and means of processing personal data (names, email addresses, etc.).</p>
<h3>Revocation of your consent to the processing of your data</h3> <p>Many data processing operations are only possible with your express consent. You may revoke your consent at any time with future effect. An informal email making this request is sufficient. The data processed before we receive your request may still be legally processed.</p>
<h3>Right to file complaints with regulatory authorities</h3> <p>If there has been a breach of data protection legislation, the person affected may file a complaint with the competent regulatory authorities. The competent regulatory authority for matters related to data protection legislation is the data protection officer of the state in which our company is headquartered. A list of data protection officers and their contact details can be found at the following link: <a href="https://www.bfdi.bund.de/DE/Infothek/Anschriften_Links/anschriften_links-node.html" target="_blank">https://www.bfdi.bund.de/DE/Infothek/Anschriften_Links/anschriften_links-node.html</a>.</p>
<h3>Right to data portability</h3> <p>You have the right to have data which we process based on your consent or in fulfillment of a contract automatically delivered to yourself or to a third party in a standard, machine-readable format. If you require the direct transfer of data to another responsible party, this will only be done to the extent technically feasible.</p>
<h3>Information, blocking, deletion</h3> <p>As permitted by law, you have the right to be provided at any time with information free of charge about any of your personal data that is stored as well as its origin, the recipient and the purpose for which it has been processed. You also have the right to have this data corrected, blocked or deleted. You can contact us at any time using the address given in our legal notice if you have further questions on the topic of personal data.</p>
<h3>Opposition to promotional emails</h3> <p>We hereby expressly prohibit the use of contact data published in the context of website legal notice requirements with regard to sending promotional and informational materials not expressly requested. The website operator reserves the right to take specific legal action if unsolicited advertising material, such as email spam, is received.</p>

<h2>3. Data collection on our website</h2>
<h3>Cookies</h3> <p>Some of our web pages use cookies. Cookies do not harm your computer and do not contain any viruses. Cookies help make our website more user-friendly, efficient, and secure. Cookies are small text files that are stored on your computer and saved by your browser.</p><p><br></p><p>Most of the cookies we use are so-called "session cookies." They are automatically deleted after your visit. Other cookies remain in your device's memory until you delete them. These cookies make it possible to recognize your browser when you next visit the site.</p><p><br></p><p>You can configure your browser to inform you about the use of cookies so that you can decide on a case-by-case basis whether to accept or reject a cookie. Alternatively, your browser can be configured to automatically accept cookies under certain conditions or to always reject them, or to automatically delete cookies when closing your browser. Disabling cookies may limit the functionality of this website.</p><p><br></p><p>Cookies which are necessary to allow electronic communications or to provide certain functions you wish to use (such as the shopping cart) are stored pursuant to Art. 6 paragraph 1, letter f of GDPR. The website operator has a legitimate interest in the storage of cookies to ensure an optimized service provided free of technical errors. If other cookies (such as those used to analyze your surfing behavior) are also stored, they will be treated separately in this privacy policy.</p>
<h3>Server log files</h3> <p>The website provider automatically collects and stores information that your browser automatically transmits to us in "server log files". These are:</p> <ul> <li>Browser type and browser version</li> <li>Operating system used</li> <li>Referrer URL</li> <li>Host name of the accessing computer</li> <li>Time of the server request</li> <li>IP address</li> </ul> <p>These data will not be combined with data from other sources.</p><p><br></p><p>The basis for data processing is Art. 6 (1) (b) GDPR, which allows the processing of data to fulfill a contract or for measures preliminary to a contract.</p>
<h3>Contact form</h3> <p>Should you send us questions via the contact form, we will collect the data entered on the form, including the contact details you provide, to answer your question and any follow-up questions. We do not share this information without your permission.</p><p><br></p><p>We will, therefore, process any data you enter onto the contact form only with your consent per Art. 6 (1)(a) GDPR. You may revoke your consent at any time. An informal email making this request is sufficient. The data processed before we receive your request may still be legally processed.</p><p><br></p><p>We will retain the data you provide on the contact form until you request its deletion, revoke your consent for its storage, or the purpose for its storage no longer pertains (e.g. after fulfilling your request). Any mandatory statutory provisions, especially those regarding mandatory data retention periods, remain unaffected by this provision.</p>
<h3>Registration on this website</h3> <p>You can register on our website in order to access additional functions offered here. The input data will only be used for the purpose of using the respective site or service for which you have registered. The mandatory information requested during registration must be provided in full. Otherwise, we will reject your registration.</p><p><br></p><p>To inform you about important changes such as those within the scope of our site or technical changes, we will use the email address specified during registration.</p><p><br></p><p>We will process the data provided during registration only based on your consent per Art. 6 (1)(a) GDPR. You may revoke your consent at any time with future effect. An informal email making this request is sufficient. The data processed before we receive your request may still be legally processed.</p><p><br></p><p>We will continue to store the data collected during registration for as long as you remain registered on our website. Statutory retention periods remain unaffected.</p>
<h3>Registration with Facebook Connect</h3> <p>Instead of registering directly on our website, you may also register using Facebook Connect. This service is provided by Facebook Ireland Limited, 4 Grand Canal Square, Dublin 2, Ireland.</p><p><br></p><p>If you decide to register with Facebook Connect, you will be automatically redirected to the Facebook platform. There you can log in with your Facebook username and password. This will link your Facebook profile to our website or services. This link gives us access to your data stored on Facebook. Including especially your:</p> <ul> <li>Facebook name</li> <li>Facebook profile picture</li> <li>Email address provided to Facebook</li> <li>Facebook ID</li> <li>Birthday</li> <li>Gender</li> <li>Country</li> </ul> <p>This data will be used to set up, provide, and personalize your account.</p><p><br></p><p>For more information, see Facebook's Terms of Use and Privacy Policy. These can be found at <a href="https://www.facebook.com/about/privacy/" target="_blank">https://www.facebook.com/about/privacy/</a> and <a href="https://www.facebook.com/legal/terms/" target="_blank">https://www.facebook.com/legal/terms/</a>.</p>
<h3>Registration with Google+</h3> <p>Instead of registering directly on our website, you may also register using Google+. This service is provided by Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA.</p><p><br></p><p>If you decide to register with Google+, you will be automatically redirected to the Google+ platform. There you can log in with your Google+ username and password. This will link your Google+ profile to our website or services. This link gives us access to your data stored on Google+. Including especially your:</p> <ul> <li>Google+ name</li> <li>Google+ profile picture</li> <li>Google+ cover picture</li> <li>Email address provided to Google+</li> <li>Google+ ID</li> <li>Birthday</li> <li>Gender</li> <li>Country</li> </ul> <p>This data will be used to set up, provide, and personalize your account.</p><p><br></p><p>For more information, see Google's Terms of Use and Privacy Policy. These can be found at <a href="https://policies.google.com/terms" target="_blank">https://policies.google.com/terms</a>, <a href="https://www.google.com/+/policy/pagesterms.html" target="_blank">https://www.google.com/+/policy/pagesterms.html</a> and <a href="https://policies.google.com/privacy" target="_blank">https://policies.google.com/privacy</a>.</p>
<h3>Registration with Twitter</h3> <p>Instead of registering directly on our website, you may also register using Twitter. This service is provided by Twitter Inc., 1355 Market Street, Suite 900, San Francisco, CA 94103, USA.</p><p><br></p><p>If you decide to register with Twitter, you will be automatically redirected to the Twitter platform. There you can log in with your Twitter username and password. This will link your Twitter profile to our website or services. This link gives us access to your data stored on Twitter. Including especially your:</p> <ul> <li>Twitter name</li> <li>Twitter profile picture</li> <li>Twitter cover picture</li> <li>Email address provided to Twitter</li> <li>Twitter ID</li> <li>Birthday</li> <li>Gender</li> <li>Country</li> </ul> <p>This data will be used to set up, provide, and personalize your account.</p><p><br></p><p>For more information, see Twitter's Terms of Use and Privacy Policy. These can be found at <a href="https://twitter.com/tos" target="_blank">https://twitter.com/tos</a> and <a href="https://twitter.com/privacy" target="_blank">https://twitter.com/privacy</a>.</p>
<h3>Registration with GitHub</h3> <p>Instead of registering directly on our website, you may also register using GitHub. This service is provided by GitHub, Inc, 88 Colin P Kelly Jr St, San Francisco, CA 94107, USA.</p><p><br></p><p>If you decide to register with GitHub, you will be automatically redirected to the GitHub platform. There you can log in with your GitHub username and password. This will link your GitHub profile to our website or services. This link gives us access to your data stored on GitHub. Including especially your:</p> <ul> <li>GitHub name</li> <li>GitHub profile picture</li> <li>GitHub cover picture</li> <li>Email address provided to GitHub</li> <li>GitHub ID</li> <li>Birthday</li> <li>Gender</li> <li>Country</li> </ul> <p>This data will be used to set up, provide, and personalize your account.</p><p><br></p><p>For more information, see GitHub's Terms of Use and Privacy Policy. These can be found at <a href="https://help.github.com/articles/github-terms-of-service/" target="_blank">https://help.github.com/articles/github-terms-of-service/</a> and <a href="https://help.github.com/articles/github-privacy-statement/" target="_blank">https://help.github.com/articles/github-privacy-statement/</a>.</p>
<h3>Processing of data (customer and contract data)</h3> <p>We collect, process, and use personal data only insofar as it is necessary to establish, or modify legal relationships with us (master data). This is done based on Art. 6 (1) (b) GDPR, which allows the processing of data to fulfill a contract or for measures preliminary to a contract. We collect, process and use your personal data when accessing our website (usage data) only to the extent required to enable you to access our service or to bill you for the same.</p><p><br></p><p>Collected customer data shall be deleted after completion of the order or termination of the business relationship. Legal retention periods remain unaffected.</p>
<h3>Data transferred when signing up for services and digital content</h3> <p>We transmit personally identifiable data to third parties only to the extent required to fulfill the terms of your contract with us, for example, to banks entrusted to process your payments.</p><p><br></p><p>Your data will not be transmitted for any other purpose unless you have given your express permission to do so. Your data will not be disclosed to third parties for advertising purposes without your express consent.</p><p><br></p><p>The basis for data processing is Art. 6 (1) (b) GDPR, which allows the processing of data to fulfill a contract or for measures preliminary to a contract.</p>

<h2>4. Analytics and advertising</h2>
<h3>Google reCAPTCHA</h3> <p>We use "Google reCAPTCHA" (hereinafter "reCAPTCHA") on our websites. This service is provided by Google Inc., 1600 Amphitheater Parkway, Mountain View, CA 94043, USA ("Google").</p><p><br></p><p>reCAPTCHA is used to check whether the data entered on our website (such as on a contact form) has been entered by a human or by an automated program. To do this, reCAPTCHA analyzes the behavior of the website visitor based on various characteristics. This analysis starts automatically as soon as the website visitor enters the website. For the analysis, reCAPTCHA evaluates various information (e.g. IP address, how long the visitor has been on the website, or mouse movements made by the user). The data collected during the analysis will be forwarded to Google.</p><p><br></p><p>The reCAPTCHA analyses take place completely in the background. Website visitors are not advised that such an analysis is taking place.</p><p><br></p><p>Data processing is based on Art. 6 (1) (f) GDPR. The website operator has a legitimate interest in protecting its site from abusive automated crawling and spam.</p><p><br></p><p>For more information about Google reCAPTCHA and Google's privacy policy, please visit the following links: <a href="https://www.google.com/intl/de/policies/privacy/" target="_blank">https://www.google.com/intl/de/policies/privacy/</a> and <a href="https://www.google.com/recaptcha/intro/android.html" target="_blank">https://www.google.com/recaptcha/intro/android.html</a>.</p>

<h2>5. Newsletter</h2>
<h3>Newsletter data</h3> <p>If you would like to receive our newsletter, we require a valid email address as well as information that allows us to verify that you are the owner of the specified email address and that you agree to receive this newsletter. No additional data is collected or is only collected on a voluntary basis. We only use this data to send the requested information and do not pass it on to third parties.</p><p><br></p><p>We will, therefore, process any data you enter onto the contact form only with your consent per Art. 6 (1) (a) GDPR. You can revoke consent to the storage of your data and email address as well as their use for sending the newsletter at any time, e.g. through the "unsubscribe" link in the newsletter. The data processed before we receive your request may still be legally processed.</p><p><br></p><p>The data provided when registering for the newsletter will be used to distribute the newsletter until you cancel your subscription when said data will be deleted. Data we have stored for other purposes (e.g. email addresses for the members area) remain unaffected.</p>

<h2>6. Plugins and tools</h2>
<h3>YouTube</h3> <p>Our website uses plugins from YouTube, which is operated by Google. The operator of the pages is YouTube LLC, 901 Cherry Ave., San Bruno, CA 94066, USA.</p><p><br></p><p>If you visit one of our pages featuring a YouTube plugin, a connection to the YouTube servers is established. Here the YouTube server is informed about which of our pages you have visited.</p><p><br></p><p>If you're logged in to your YouTube account, YouTube allows you to associate your browsing behavior directly with your personal profile. You can prevent this by logging out of your YouTube account.</p><p><br></p><p>YouTube is used to help make our website appealing. This constitutes a justified interest pursuant to Art. 6 (1) (f) GDPR.</p><p><br></p><p>Further information about handling user data, can be found in the data protection declaration of YouTube under <a href="https://www.google.de/intl/de/policies/privacy" target="_blank">https://www.google.de/intl/de/policies/privacy</a>.</p>
<h3>Google Web Fonts</h3> <p>For uniform representation of fonts, this page uses web fonts provided by Google. When you open a page, your browser loads the required web fonts into your browser cache to display texts and fonts correctly.</p><p><br></p><p>When you call up a page of our website that contains a social plugin, your browser makes a direct connection with Google servers. Google thus becomes aware that our web page was accessed via your IP address. The use of Google Web fonts is done in the interest of a uniform and attractive presentation of our website. This constitutes a justified interest pursuant to Art. 6 (1) (f) GDPR.</p><p><br></p><p>If your browser does not support web fonts, a standard font is used by your computer.</p><p><br></p><p>Further information about handling user data, can be found at <a href="https://developers.google.com/fonts/faq" target="_blank">https://developers.google.com/fonts/faq</a> and in Google's privacy policy at <a href="https://www.google.com/policies/privacy/" target="_blank">https://www.google.com/policies/privacy/</a>.</p>
<h3>Vimeo</h3> <p>Our website uses features provided by the Vimeo video portal. This service is provided by Vimeo Inc., 555 West 18th Street, New York, New York 10011, USA.</p><p><br></p><p>If you visit one of our pages featuring a Vimeo plugin, a connection to the Vimeo servers is established. Here the Vimeo server is informed about which of our pages you have visited. In addition, Vimeo will receive your IP address. This also applies if you are not logged in to Vimeo when you visit our website or do not have a Vimeo account. The information is transmitted to a Vimeo server in the US, where it is stored.</p><p><br></p><p>If you are logged in to your Vimeo account, Vimeo allows you to associate your browsing behavior directly with your personal profile. You can prevent this by logging out of your Vimeo account.</p><p><br></p><p>For more information on how to handle user data, please refer to the Vimeo Privacy Policy at <a href="https://vimeo.com/privacy" target="_blank">https://vimeo.com/privacy</a>.</p>
<h3>Google Maps</h3> <p>This site uses the Google Maps map service via an API. It is operated by Google Inc., 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA.</p><p><br></p><p>To use Google Maps, it is necessary to save your IP address. This information is generally transmitted to a Google server in the USA and stored there. The provider of this site has no influence on this data transfer.</p><p><br></p><p>The use of Google Maps is in the interest of making our website appealing and to facilitate the location of places specified by us on the website. This constitutes a justified interest pursuant to Art. 6 (1) (f) GDPR.</p><p><br></p><p>Further information about handling user data, can be found in the data protection declaration of Google at <a href="https://www.google.de/intl/de/policies/privacy/" target="_blank">https://www.google.de/intl/de/policies/privacy/</a>.</p>
<h3>SoundCloud</h3> <p>On our pages, plugins of the SoundCloud social network (SoundCloud Limited, Berners House, 47-48 Berners Street, London W1T 3NF, UK) may be integrated. The SoundCloud plugins can be recognized by the SoundCloud logo on our site.</p><p><br></p><p>When you visit our site, a direct connection between your browser and the SoundCloud server is established via the plugin. This enables SoundCloud to receive information that you have visited our site from your IP address. If you click on the "Like" or "Share" buttons while you are logged into your SoundCloud account, you can link the content of our pages to your SoundCloud profile. This means that SoundCloud can associate visits to our pages with your user account. We would like to point out that, as the provider of these pages, we have no knowledge of the content of the data transmitted or how it will be used by SoundCloud. For more information on SoundCloud's privacy policy, please go to <a href="https://soundcloud.com/pages/privacy" target="_blank">https://soundcloud.com/pages/privacy</a>.</p><p><br></p><p>If you do not want SoundCloud to associate your visit to our site with your SoundCloud account, please log out of your SoundCloud account.</p>
<h3>Veoh</h3> <p>Our website uses features provided by the Veoh video portal. This service is provided by FC2, 4730 South Fort Apache Road, Suite 300, Las Vegas, NV 89147, USA.</p><p><br></p><p>If you visit one of our pages featuring a Veoh plugin, a connection to the Veoh servers is established. Here the Veoh server is informed about which of our pages you have visited. In addition, Veoh will receive your IP address. This also applies if you are not logged in to Veoh when you visit our website or do not have a Veoh account. The information is transmitted to a Veoh server in the US, where it is stored.</p><p><br></p><p>If you are logged in to your Veoh account, Veoh allows you to associate your browsing behavior directly with your personal profile. You can prevent this by logging out of your Veoh account.</p><p><br></p><p>For more information on how to handle user data, please refer to the Veoh Privacy Policy at <a href="http://www.veoh.com/corporate/privacypolicy" target="_blank">http://www.veoh.com/corporate/privacypolicy</a>.</p>
<h3>Dailymotion</h3> <p>Our website uses features provided by the Dailymotion video portal. This service is provided by Dailymotion, 140 boulevard Malesherbes, 75017 Paris, France.</p><p><br></p><p>If you visit one of our pages featuring a Dailymotion plugin, a connection to the Dailymotion servers is established. Here the Dailymotion server is informed about which of our pages you have visited. In addition, Dailymotion will receive your IP address. This also applies if you are not logged in to Dailymotion when you visit our website or do not have a Dailymotion account.</p><p><br></p><p>If you are logged in to your Dailymotion account, Dailymotion allows you to associate your browsing behavior directly with your personal profile. You can prevent this by logging out of your Dailymotion account.</p><p><br></p><p>For more information on how to handle user data, please refer to the Dailymotion Privacy Policy at <a href="https://www.dailymotion.com/legal/privacy" target="_blank">https://www.dailymotion.com/legal/privacy</a>.</p>
<h3>GitHub</h3> <p>Our website uses features provided by the GitHub. This service is provided by GitHub, Inc, 88 Colin P Kelly Jr St, San Francisco, CA 94107, USA.</p><p><br></p><p>If you visit one of our pages featuring a GitHub plugin, a connection to the GitHub servers is established. Here the GitHub server is informed about which of our pages you have visited. In addition, GitHub will receive your IP address. This also applies if you are not logged in to GitHub when you visit our website or do not have a GitHub account. The information is transmitted to a GitHub server in the US, where it is stored.</p><p><br></p><p>If you are logged in to your GitHub account, GitHub allows you to associate your browsing behavior directly with your personal profile. You can prevent this by logging out of your GitHub account.</p><p><br></p><p>For more information on how to handle user data, please refer to the GitHub Privacy Policy at <a href="https://help.github.com/articles/github-privacy-statement/" target="_blank">https://help.github.com/articles/github-privacy-statement/</a>.</p>
<h3>Spotify</h3> <p>Our website uses features provided by the Spotify. This service is provided by Spotify AB, Birger Jarlsgatan 61, 113 56 Stockholm, Sweden.</p><p><br></p><p>If you visit one of our pages featuring a Spotify plugin, a connection to the Spotify servers is established. Here the Spotify server is informed about which of our pages you have visited. In addition, Spotify will receive your IP address. This also applies if you are not logged in to Spotify when you visit our website or do not have a Spotify account.</p><p><br></p><p>If you are logged in to your Spotify account, Spotify allows you to associate your browsing behavior directly with your personal profile. You can prevent this by logging out of your Spotify account.</p><p><br></p><p>For more information on how to handle user data, please refer to the Spotify Privacy Policy at <a href="https://www.spotify.com/de/legal/privacy-policy/" target="_blank">https://www.spotify.com/de/legal/privacy-policy/</a>.</p>
<h3>Instagram</h3> <p>Our website uses features provided by the Instagram. This service is provided by Instagram Inc., 1601 Willow Road, Menlo Park, CA 94025, USA.</p><p><br></p><p>If you visit one of our pages featuring a Instagram plugin, a connection to the Instagram servers is established. Here the Instagram server is informed about which of our pages you have visited. In addition, Instagram will receive your IP address. This also applies if you are not logged in to Instagram when you visit our website or do not have a Instagram account. The information is transmitted to a Instagram server in the US, where it is stored.</p><p><br></p><p>If you are logged in to your Instagram account, Instagram allows you to associate your browsing behavior directly with your personal profile. You can prevent this by logging out of your Instagram account.</p><p><br></p><p>For more information on how to handle user data, please refer to the Instagram Privacy Policy at <a href="https://instagram.com/about/legal/privacy/" target="_blank">https://instagram.com/about/legal/privacy/</a>.</p>
<h3>Imgur</h3> <p>Our website uses features provided by the Imgur. This service is provided by Imgur, Inc., 415 Jackson Street, 2nd Floor, Suite 200, San Francisco, CA 94111, USA.</p><p><br></p><p>If you visit one of our pages featuring a Imgur plugin, a connection to the Imgur servers is established. Here the Imgur server is informed about which of our pages you have visited. In addition, Imgur will receive your IP address. This also applies if you are not logged in to Imgur when you visit our website or do not have a Imgur account. The information is transmitted to a Imgur server in the US, where it is stored.</p><p><br></p><p>If you are logged in to your Imgur account, Imgur allows you to associate your browsing behavior directly with your personal profile. You can prevent this by logging out of your Imgur account.</p><p><br></p><p>For more information on how to handle user data, please refer to the Imgur Privacy Policy at <a href="https://imgur.com/privacy" target="_blank">https://imgur.com/privacy</a>.</p>
<h3>Twitch</h3> <p>Our website uses features provided by the Twitch. This service is provided by Twitch Interactive, Inc., 225 Bush Street, 6th Floor, San Francisco, CA 94104, USA.</p><p><br></p><p>If you visit one of our pages featuring a Twitch plugin, a connection to the Twitch servers is established. Here the Twitch server is informed about which of our pages you have visited. In addition, Twitch will receive your IP address. This also applies if you are not logged in to Twitch when you visit our website or do not have a Twitch account. The information is transmitted to a Twitch server in the US, where it is stored.</p><p><br></p><p>If you are logged in to your Twitch account, Twitch allows you to associate your browsing behavior directly with your personal profile. You can prevent this by logging out of your Twitch account.</p><p><br></p><p>For more information on how to handle user data, please refer to the Twitch Privacy Policy at <a href="https://www.twitch.tv/p/legal/privacy-policy/" target="_blank">https://www.twitch.tv/p/legal/privacy-policy/</a>.</p>

<h2>7. Payment service providers</h2>
<h3>PayPal</h3> <p>Our website accepts payments via PayPal. The provider of this service is PayPal (Europe) S.à.r.l & Cie, S.C.A. (22-24 Boulevard Royal, L-2449 Luxembourg.</p><p><br></p><p>If you select payment via PayPal, the payment data you provide will be supplied to PayPal based on Art. 6 (1) (a) (Consent) and Art. 6 (1) (b) GDPR (Processing for contract purposes). You have the option to revoke your consent at any time with future effect. It does not affect the processing of data previously collected.</p>
CONTENT_EN;



$hashes = [];
$languages = LanguageFactory::getInstance()->getLanguages();
$languageIDs = [];
foreach ($languages as $language) {
	if ($language->languageCode == 'de' || $language->languageCode == 'en') {
		$languageIDs[] = $language->languageID;
		
		// the hash for `de` is `75ee56f38ace5914116f144886eeaf1bc0c6ea05`
		// the hash for `en` is `5cc3153040d5f618cf5e6e604a251264259fa606`
		$hashes[$language->languageCode] = ($language->languageCode == 'de') ? '75ee56f38ace5914116f144886eeaf1bc0c6ea05' : '5cc3153040d5f618cf5e6e604a251264259fa606';
	}
}
$conditions = new PreparedStatementConditionBuilder();
$conditions->add("languageID IN (?)", [$languageIDs]);
$conditions->add("pageID = (SELECT pageID FROM wcf".WCF_N."_page WHERE identifier = ?)", ['com.woltlab.wcf.PrivacyPolicy']);
$sql = "SELECT  pageContentID, pageID, languageID, content
	FROM    wcf".WCF_N."_page_content
	".$conditions;
$statement = WCF::getDB()->prepareStatement($sql);
$statement->execute($conditions->getParameters());
$data = [];
$pageID = 0;
while ($row = $statement->fetchArray()) {
	// Process the content by extracting the text and discarding anything
	// that is not a-z and A-Z, which preserves almost the entire text, but
	// strips anything that could be subject to minor changes without
	// changing the meaning, such as whitespaces.
	$processor = new \wcf\system\html\input\HtmlInputProcessor();
	$processor->processIntermediate($row['content']);
	$content = $processor->getTextContent();
	$content = preg_replace('~[^a-zA-Z]~', '', $content);
	
	$languageCode = LanguageFactory::getInstance()->getLanguage($row['languageID'])->languageCode;
	if (sha1($content) !== $hashes[$languageCode]) {
		// The content does not match, do not risk overwriting any
		// user-made changes and skip this language.
		continue;
	}
	
	$data[$row['pageContentID']] = ($languageCode == 'de') ? $content_de : $content_en;
	$pageID = $row['pageID'];
}

if (!empty($data)) {
	$sql = "UPDATE  wcf".WCF_N."_page_content
		SET     content = ?
		WHERE   pageContentID = ?";
	$statement = WCF::getDB()->prepareStatement($sql);
	foreach ($data as $pageContentID => $content) {
		$statement->execute([
			$content,
			$pageContentID
		]);
	}
	
	$sql = "UPDATE  wcf".WCF_N."_page
		SET     lastUpdateTime = ?
		WHERE   pageID = ?";
	$statement = WCF::getDB()->prepareStatement($sql);
	$statement->execute([
		TIME_NOW,
		$pageID
	]);
}
