<?php

namespace wcf\system\cache\source;

use ParagonIE\ConstantTime\Hex;
use wcf\system\io\AtomicWriter;
use wcf\system\WCF;

/**
 * DiskCacheSource is an implementation of CacheSource that stores the cache as simple files in the file system.
 *
 * @author  Alexander Ebert, Marcel Werk
 * @copyright   2001-2024 WoltLab GmbH
 * @license GNU Lesser General Public License <http://opensource.org/licenses/lgpl-license.php>
 */
final class DiskCacheSource
{
    /**
     * Flushes a specific cache, optionally removing caches which share the same name.
     */
    public function flush(string $cacheName, bool $useWildcard): void
    {
        if ($useWildcard) {
            $quoted = \preg_quote($cacheName, '/');
            $regex = "/^cache\\.{$quoted}(-[a-f0-9]+)?\\.v3\\.php$/";

            $iterator = new \DirectoryIterator(\WCF_DIR . 'cache/');
            foreach ($iterator as $file) {
                if (!$file->isFile()) {
                    continue;
                }
                if ($file->getExtension() !== 'php') {
                    continue;
                }
                if (!\preg_match($regex, $file->getBasename())) {
                    continue;
                }

                WCF::resetZendOpcache($file->getPathname());

                if (!@\touch($file->getPathname(), 1)) {
                    \unlink($file->getPathname());
                }
            }
        } else {
            $filename = $this->getFilename($cacheName);

            if (\file_exists($filename)) {
                WCF::resetZendOpcache($filename);

                if (!@\touch($filename, 1)) {
                    \unlink($filename);
                }
            }
        }
    }

    /**
     * Clears the cache completely.
     */
    public function flushAll(): void
    {
        $iterator = new \DirectoryIterator(\WCF_DIR . 'cache/');
        foreach ($iterator as $file) {
            if (!$file->isFile()) {
                continue;
            }
            if ($file->getExtension() !== 'php') {
                continue;
            }

            \unlink($file->getPathname());
        }

        WCF::resetZendOpcache();
    }

    /**
     * Returns a cached variable.
     */
    public function get(string $cacheName, int $maxLifetime): mixed
    {
        $filename = $this->getFilename($cacheName);
        if ($this->needRebuild($filename, $maxLifetime)) {
            return null;
        }

        // load cache
        try {
            return $this->readCache($filename);
        } catch (\Exception $e) {
            return null;
        }
    }

    /**
     * Stores a variable in the cache.
     */
    public function set(string $cacheName, mixed $value, int $maxLifetime): void
    {
        $serializedValue = \serialize($value);

        // Generate a secure boundary that does not appear in the serialized
        // content in order to protect against cache poisoning/RCE. This allows
        // us to continue utilizing the OPcache without being vulnerable.
        //
        // This identifier is generated randomly for each cache so that an
        // attacker cannot use the knowledge of an existing cache to provide a
        // crafted payload since the identifier changes with every rebuild.
        $boundary = null;
        for ($i = 0; $i < 3; $i++) {
            // 128 bits of entropy is more than sufficient and in the extremely
            // unlikely case of a collision, it will be retried twice in order
            // to avoid failing hard immediately.
            $candidate = \sprintf(
                'BOUNDARY_%s',
                \strtoupper(
                    Hex::encode(
                        \random_bytes(16)
                    )
                ),
            );

            if (!\str_contains($serializedValue, $candidate)) {
                $boundary = $candidate;
                break;
            }
        }

        if ($boundary === null) {
            throw new \RuntimeException("Failed to generate a secure boundary.");
        }

        $writer = new AtomicWriter($this->getFilename($cacheName));
        $writer->write("<?php /* cache: " . $cacheName . " (generated at " . \gmdate('r') . ") DO NOT EDIT THIS FILE */ return <<<'{$boundary}'\n");
        $writer->write($serializedValue);
        $writer->write("\n{$boundary};\n");
        $writer->flush();
        $writer->close();

        WCF::resetZendOpcache($this->getFilename($cacheName));
    }

    /**
     * Returns cache filename.
     */
    private function getFilename(string $cacheName): string
    {
        return \WCF_DIR . 'cache/cache.' . $cacheName . '.v3.php';
    }

    /**
     * Determines whether the cache needs to be rebuild or not.
     */
    private function needRebuild(string $filename, int $maxLifetime): bool
    {
        // cache does not exist
        if (!\file_exists($filename)) {
            return true;
        }

        // cache is empty
        if (!@\filesize($filename)) {
            return true;
        }

        // cache resource was marked as obsolete
        if (($mtime = \filemtime($filename)) <= 1) {
            return true;
        }

        // maxlifetime expired
        if ($maxLifetime > 0 && (\TIME_NOW - $mtime) > $maxLifetime) {
            return true;
        }

        // do not rebuild cache
        return false;
    }

    /**
     * Loads the file of a cached resource.
     */
    private function readCache(string $filename): mixed
    {
        $contents = include($filename);

        try {
            return \unserialize($contents);
        } catch (\Throwable $e) {
            throw new \Exception("Failed to unserialize the cache contents.", 0, $e);
        }
    }

    /**
     * Returns the timestamp when the cache was created.
     * Or `null` if the cache does not exist or is empty.
     */
    public function getCreationTime(string $cacheName, int $maxLifetime): ?int
    {
        $filename = $this->getFilename($cacheName);

        if (!\file_exists($filename)) {
            return null;
        }

        if (!@\filesize($filename)) {
            return null;
        }

        return \filemtime($filename);
    }
}
