name: XML

on:
  push:
    branches:
    - "6.0"
    - "6.1"
    - "6.2"
    - "6.3"
    paths:
    - "com.woltlab.wcf/*.xml"
  pull_request:
    paths:
    - "com.woltlab.wcf/*.xml"

permissions:
  contents: read

jobs:
  syntax:
    name: Check Syntax
    runs-on: ubuntu-latest
    steps:
    - name: Install xmllint
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends libxml2-utils
    - name: Checkout
      uses: actions/checkout@v6
    - name: Run xmllint
      run: |
        ! find com.woltlab.wcf/ -type f -name '*.xml' -exec xmllint --noout '{}' \; 2>&1 | grep -v '^$'
